// <auto-generated />
using System;
using EmployeeMvc.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeMvc.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250828103158_I1")]
    partial class I1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeMvc.Models.Department", b =>
                {
                    b.Property<string>("DepartmentId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("AutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutoId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DepartmentShortName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = "001",
                            AutoId = 0,
                            DepartmentName = "Software Department"
                        },
                        new
                        {
                            DepartmentId = "002",
                            AutoId = 0,
                            DepartmentName = "Quality Department"
                        },
                        new
                        {
                            DepartmentId = "003",
                            AutoId = 0,
                            DepartmentName = "Human Resources"
                        },
                        new
                        {
                            DepartmentId = "004",
                            AutoId = 0,
                            DepartmentName = "Finance"
                        },
                        new
                        {
                            DepartmentId = "005",
                            AutoId = 0,
                            DepartmentName = "Marketing"
                        },
                        new
                        {
                            DepartmentId = "006",
                            AutoId = 0,
                            DepartmentName = "Sales"
                        },
                        new
                        {
                            DepartmentId = "007",
                            AutoId = 0,
                            DepartmentName = "Administration"
                        },
                        new
                        {
                            DepartmentId = "008",
                            AutoId = 0,
                            DepartmentName = "Accounts"
                        });
                });

            modelBuilder.Entity("EmployeeMvc.Models.Designation", b =>
                {
                    b.Property<string>("DesignationId")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("AutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutoId"));

                    b.Property<string>("DesignationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DesingnationShortname")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DesignationId");

                    b.ToTable("Designations");

                    b.HasData(
                        new
                        {
                            DesignationId = "001",
                            AutoId = 0,
                            DesignationName = "Software Developer"
                        },
                        new
                        {
                            DesignationId = "002",
                            AutoId = 0,
                            DesignationName = "Manager"
                        },
                        new
                        {
                            DesignationId = "003",
                            AutoId = 0,
                            DesignationName = "Team Leader"
                        },
                        new
                        {
                            DesignationId = "004",
                            AutoId = 0,
                            DesignationName = "Senior Developer"
                        },
                        new
                        {
                            DesignationId = "005",
                            AutoId = 0,
                            DesignationName = "Junior Developer"
                        },
                        new
                        {
                            DesignationId = "006",
                            AutoId = 0,
                            DesignationName = "Business Analyst"
                        },
                        new
                        {
                            DesignationId = "007",
                            AutoId = 0,
                            DesignationName = "Chief Technology Officer"
                        },
                        new
                        {
                            DesignationId = "008",
                            AutoId = 0,
                            DesignationName = "Quality Assurance"
                        },
                        new
                        {
                            DesignationId = "009",
                            AutoId = 0,
                            DesignationName = "Administration Officer"
                        },
                        new
                        {
                            DesignationId = "010",
                            AutoId = 0,
                            DesignationName = "Executive Marketing"
                        },
                        new
                        {
                            DesignationId = "011",
                            AutoId = 0,
                            DesignationName = "Senior Sales "
                        },
                        new
                        {
                            DesignationId = "012",
                            AutoId = 0,
                            DesignationName = "Business Development Manager"
                        });
                });

            modelBuilder.Entity("EmployeeMvc.Models.Devskill", b =>
                {
                    b.Property<string>("DevId")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("AutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutoId"));

                    b.Property<string>("DevName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DevShortName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DevId");

                    b.ToTable("Devskills");

                    b.HasData(
                        new
                        {
                            DevId = "001",
                            AutoId = 0,
                            DevName = "C# Programming",
                            DevShortName = "C#"
                        },
                        new
                        {
                            DevId = "002",
                            AutoId = 0,
                            DevName = "JavaScript",
                            DevShortName = "JS"
                        },
                        new
                        {
                            DevId = "003",
                            AutoId = 0,
                            DevName = "ASP .NET CORE",
                            DevShortName = "CORE"
                        },
                        new
                        {
                            DevId = "004",
                            AutoId = 0,
                            DevName = "SQL Database",
                            DevShortName = "SQL"
                        },
                        new
                        {
                            DevId = "005",
                            AutoId = 0,
                            DevName = "SQL Server Management Studio",
                            DevShortName = "SQL Server"
                        },
                        new
                        {
                            DevId = "006",
                            AutoId = 0,
                            DevName = ".NET Framework",
                            DevShortName = ".NET"
                        },
                        new
                        {
                            DevId = "007",
                            AutoId = 0,
                            DevName = "ASP.NET MVC",
                            DevShortName = "MVC"
                        },
                        new
                        {
                            DevId = "008",
                            AutoId = 0,
                            DevName = "Web API Development",
                            DevShortName = "API"
                        },
                        new
                        {
                            DevId = "009",
                            AutoId = 0,
                            DevName = "HTML/CSS",
                            DevShortName = "HTML"
                        },
                        new
                        {
                            DevId = "010",
                            AutoId = 0,
                            DevName = "Angular Framework",
                            DevShortName = "Angular"
                        },
                        new
                        {
                            DevId = "011",
                            AutoId = 0,
                            DevName = "React Library",
                            DevShortName = "React"
                        },
                        new
                        {
                            DevId = "012",
                            AutoId = 0,
                            DevName = "Python Programming",
                            DevShortName = "Python"
                        },
                        new
                        {
                            DevId = "013",
                            AutoId = 0,
                            DevName = "C++ Programming",
                            DevShortName = "C++"
                        });
                });

            modelBuilder.Entity("EmployeeMvc.Models.Educationalinfo", b =>
                {
                    b.Property<int>("EducationalinfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EducationalinfoID"));

                    b.Property<int>("AutoId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExamTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Institution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PassingYear")
                        .HasColumnType("int");

                    b.Property<decimal?>("Result")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EducationalinfoID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Educationalinfos");
                });

            modelBuilder.Entity("EmployeeMvc.Models.Employeeinfo", b =>
                {
                    b.Property<string>("EmployeeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AutoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutoID"));

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Designation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DevSkills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrossSalary")
                        .HasColumnType("int");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employeeinfos");
                });

            modelBuilder.Entity("EmployeeMvc.Models.Educationalinfo", b =>
                {
                    b.HasOne("EmployeeMvc.Models.Employeeinfo", "Employeeinfo")
                        .WithMany("Educationalinfos")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employeeinfo");
                });

            modelBuilder.Entity("EmployeeMvc.Models.Employeeinfo", b =>
                {
                    b.Navigation("Educationalinfos");
                });
#pragma warning restore 612, 618
        }
    }
}
